IlanSistemi/Models/Entitites/Category.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace IlanSistemi.Models.Entitites
{
    public class Category
    {
        [DisplayName("Kategori No")]
        public int CategoryId { get; set; }


        [DisplayName("Kategori Adı")]
        [Required(ErrorMessage = "'Kategori Adı' zorunlu alandır.")]
        public string CategoryName { get; set; }


        [DisplayName("Kategori Görsel Url")]
        public string ImageUrl { get; set; }
    }
}

IlanSistemi/Controllers/AdvertisementsController.cs
using IlanSistemi.Models;
using IlanSistemi.Models.Entitites;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;

namespace IlanSistemi.Controllers
{
    public class AdvertisementsController : Controller
    {
        SqlConnection connection = new SqlConnection();
        public AdvertisementsController(IConfiguration configuration)
        {
            connection.ConnectionString = configuration.GetConnectionString("IlanSistemi");
        }
        public IActionResult Index()
        {
            SqlDataAdapter sqlData = new SqlDataAdapter("select * from dbo.Advertisements as a inner join dbo.Categories as c on c.CategoryId=a.CategoryId order by PublicationDate desc", connection);
            DataTable table = new DataTable();
            sqlData.Fill(table);

            List<AdViewModel> adViews = new List<AdViewModel>();

            foreach (DataRow data in table.Rows)
            {
                AdViewModel model = new AdViewModel
                {
                    TitleId = Convert.ToInt32(data["TitleId"]),
                    TitleName = (data["TitleName"]).ToString(),
                    CategoryId = Convert.ToInt32(data["CategoryId"]),
                    CategoryName = (data["CategoryName"]).ToString(),
                    Description = (data["Description"]).ToString(),
                    ListelemeUrl = (data["ListelemeUrl"]).ToString(),
                    DetayUrl = (data["DetayUrl"]).ToString(),
                    Price = Convert.ToDecimal(data["Price"]),
                    PublicationDate = Convert.ToDateTime(data["PublicationDate"]),
                };
                adViews.Add(model);
            }
            return View(adViews);
        }

        public IActionResult Create()
        {
            AdCategoryListView listView = new AdCategoryListView();
            listView.Advertisement = new Advertisement();
            listView.Categories = GetCategories();

            return View(listView);
        }

        [HttpPost]
        public IActionResult Create(AdCategoryListView model) //index view inda asp-for-titleid olarak göndermeliyiz çünkü parametremizin adı titleid olarak verdik
        {
            if (ModelState.IsValid)
            {
                SqlCommand cmd = new SqlCommand("insert into dbo.Advertisements values (@titleName, @price, @publicationDate ,@description,@categoryId, @listelemeUrl, @detayUrl)", connection);
                cmd.Parameters.AddWithValue("titleName", model.Advertisement.TitleName);
                cmd.Parameters.AddWithValue("price", model.Advertisement.Price);
                cmd.Parameters.AddWithValue("publicationDate", model.Advertisement.PublicationDate);
                cmd.Parameters.AddWithValue("description", model.Advertisement.Description);
                cmd.Parameters.AddWithValue("categoryId", model.Advertisement.CategoryId);
                cmd.Parameters.AddWithValue("listelemeUrl", model.Advertisement.ListelemeUrl);
                cmd.Parameters.AddWithValue("detayUrl", model.Advertisement.DetayUrl);

                connection.Open();
                cmd.ExecuteNonQuery();
                connection.Close();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                AdCategoryListView listView = new AdCategoryListView
                {
                    Advertisement = model.Advertisement,
                    Categories = GetCategories(),
                };

                return View(listView);
            }


        }
        public List<Category> GetCategories()
        {
            List<Category> list = new List<Category>();

            SqlDataAdapter da = new SqlDataAdapter("select * from dbo.Categories", connection);
            DataTable dt = new DataTable();
            da.Fill(dt);


            foreach (DataRow row in dt.Rows)
            {
                list.Add(new Category
                {
                    CategoryId = Convert.ToInt32(row["CategoryId"]),
                    CategoryName = row["CategoryName"].ToString(),
                    ImageUrl = row["ImageUrl"].ToString()
                });
            }

            return list;
        }

        public Advertisement GetAdvertisement(int id)
        {
            SqlDataAdapter da = new SqlDataAdapter("select * from dbo.Advertisements where TitleId=@TitleId", connection);
            da.SelectCommand.Parameters.AddWithValue("TitleId", id);
            DataTable dt = new DataTable();
            da.Fill(dt);

            Advertisement advertisement = new Advertisement
            {
                TitleId = Convert.ToInt32(dt.Rows[0]["TitleId"]),
                TitleName = dt.Rows[0]["TitleName"].ToString(),
                CategoryId = Convert.ToInt32(dt.Rows[0]["CategoryId"]),
                Description = dt.Rows[0]["Description"].ToString(),
                DetayUrl = dt.Rows[0]["DetayUrl"].ToString(),
                ListelemeUrl = dt.Rows[0]["ListelemeUrl"].ToString(),
                Price = Convert.ToDecimal(dt.Rows[0]["Price"]),
                PublicationDate = Convert.ToDateTime(dt.Rows[0]["PublicationDate"]),
            };
            return advertisement;
        }

        public AdViewModel GetAdViewModel(int id)
        {
            SqlDataAdapter da = new SqlDataAdapter("select * from dbo.Advertisements as a inner join dbo.Categories as c on c.CategoryId=a.CategoryId", connection);
            da.SelectCommand.Parameters.AddWithValue("CategoryId", id);
            DataTable table = new DataTable();
            da.Fill(table);

            AdViewModel adViewModel = new AdViewModel
            {
                TitleId = Convert.ToInt32(table.Rows[0]["TitleId"]),
                TitleName = (table.Rows[0]["TitleName"]).ToString(),
                CategoryName = (table.Rows[0]["CategoryName"]).ToString(),
                CategoryId = Convert.ToInt32(table.Rows[0]["CategoryId"]),
                Description = (table.Rows[0]["Description"]).ToString(),
                DetayUrl = (table.Rows[0]["DetayUrl"]).ToString(),
                ListelemeUrl = (table.Rows[0]["ListelemeUrl"]).ToString(),
                Price = Convert.ToDecimal(table.Rows[0]["Price"]),
                PublicationDate = Convert.ToDateTime(table.Rows[0]["PublicationDate"]),
            };

            return adViewModel;
        }



        public IActionResult Edit(int id) 
        {
            ViewBag.KategoriListesi = GetCategories();


            return View(GetAdvertisement(id));
        }


        [HttpPost]
        public IActionResult Edit(Advertisement advertisement)
        {
            if (ModelState.IsValid)
            {
                SqlCommand cmd = new SqlCommand("update dbo.Advertisements set TitleName=@titleName, Price=@price, PublicationDate=@publicationDate, Description=@description, CategoryId=@categoryId, ListelemeUrl=@listelemeUrl, DetayUrl=@detayUrl where TitleId=@titleId", connection);

                cmd.Parameters.AddWithValue("titleName", advertisement.TitleName);
                cmd.Parameters.AddWithValue("price", advertisement.Price);
                cmd.Parameters.AddWithValue("publicationDate", advertisement.PublicationDate);
                cmd.Parameters.AddWithValue("description", advertisement.Description);
                cmd.Parameters.AddWithValue("categoryId", advertisement.CategoryId);
                cmd.Parameters.AddWithValue("listelemeUrl", advertisement.ListelemeUrl);
                cmd.Parameters.AddWithValue("detayUrl", advertisement.DetayUrl);
                cmd.Parameters.AddWithValue("titleId", advertisement.TitleId);

                connection.Open();
                cmd.ExecuteNonQuery();
                connection.Close();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.KategoriListesi = GetCategories();

                return View(advertisement);
            }

        }


        public IActionResult Delete(int id)
        {
            return View(GetAdViewModel(id));
        }


        [HttpPost]
        public IActionResult Delete(Advertisement adv)
        {
            AdViewModel viewModel = GetAdViewModel(adv.TitleId);
            if(viewModel == null)
            {
                ModelState.AddModelError(string.Empty, adv.TitleId + "numaralı kayıt bulunamadı.");
                return View(viewModel);
            }
            else
            {
                SqlCommand cmd = new SqlCommand("delete from dbo.Advertisements where TitleId=@id",connection);
                cmd.Parameters.AddWithValue("id", adv.TitleId);
                connection.Open();
                cmd.ExecuteNonQuery();
                connection.Close();

                return RedirectToAction(nameof(Index));
            }

        }

    }
}

IlanSistemi/Controllers/CategoriesController.cs
using IlanSistemi.Models;
using IlanSistemi.Models.Entitites;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using NuGet.Protocol.Plugins;
using System.Data;

namespace IlanSistemi.Controllers
{
    public class CategoriesController : Controller
    {
        SqlConnection sqlConnection = new SqlConnection();
        public CategoriesController(IConfiguration configuration)
        {
            sqlConnection.ConnectionString = configuration.GetConnectionString("IlanSistemi");
        }
        public IActionResult Index()
        {
            SqlDataAdapter adapter = new SqlDataAdapter("select * from dbo.Categories order by CategoryId", sqlConnection);
            DataTable dt = new DataTable();
            adapter.Fill(dt);


            List<Category> list = new List<Category>();

            foreach (DataRow row in dt.Rows)
            {
                Category category = new Category();
                category.CategoryId = Convert.ToInt32(row["CategoryId"]);
                category.CategoryName = row["CategoryName"].ToString();
                category.ImageUrl = row["ImageUrl"].ToString();

                list.Add(category);
            }

            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(Category model)
        {
            if (ModelState.IsValid)
            {
                SqlCommand sqlCommand = new SqlCommand("insert into dbo.Categories values (@CategoryName, @ImageUrl)", sqlConnection);
                sqlCommand.Parameters.AddWithValue("CategoryName", model.CategoryName);
                sqlCommand.Parameters.AddWithValue("ImageUrl", model.ImageUrl);

                sqlConnection.Open();
                sqlCommand.ExecuteNonQuery();
                sqlConnection.Close();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }


        }


        public IActionResult Edit(int CategoryId)
        {
            SqlDataAdapter da = new SqlDataAdapter("select * from dbo.Categories where CategoryId=@CategoryId", sqlConnection);
            da.SelectCommand.Parameters.AddWithValue("CategoryId", CategoryId);
            DataTable dt = new DataTable();
            da.Fill(dt);

            if (dt.Rows.Count == 0)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                Category category = new Category();
                category.CategoryId = Convert.ToInt32(dt.Rows[0]["CategoryId"]);
                category.CategoryName = dt.Rows[0]["CategoryName"].ToString();
                category.ImageUrl = dt.Rows[0]["ImageUrl"].ToString();

                return View(category);
            };
        }


        [HttpPost]
        public IActionResult Edit(Category model)
        {
            SqlDataAdapter da = new SqlDataAdapter("select * from dbo.Categories where CategoryId=@CategoryId", sqlConnection);
            da.SelectCommand.Parameters.AddWithValue("CategoryId", model.CategoryId);

            DataTable dt = new DataTable();
            da.Fill(dt);

            if (dt.Rows.Count == 0)
            {
                ModelState.AddModelError(string.Empty, model.CategoryId + "numaralı kayıt bulunamadı.");
                return View(model);
            }
            else
            {
                SqlCommand cmd = new SqlCommand("update dbo.Categories set CategoryName=@CategoryName, ImageUrl=@ImageUrl where CategoryId=@CategoryId", sqlConnection);
                cmd.Parameters.AddWithValue("CategoryId", model.CategoryId);
                cmd.Parameters.AddWithValue("CategoryName", model.CategoryName);
                cmd.Parameters.AddWithValue("ImageUrl", model.ImageUrl);

                sqlConnection.Open();
                cmd.ExecuteNonQuery();
                sqlConnection.Close();

                return RedirectToAction(nameof(Index));
            }
        }



        public IActionResult Delete(int CategoryId)
        {
            SqlDataAdapter adapter = new SqlDataAdapter("select * from dbo.Categories where CategoryId=@CategoryId", sqlConnection);
            adapter.SelectCommand.Parameters.AddWithValue("CategoryId", CategoryId);
            DataTable dataTable = new DataTable();
            adapter.Fill(dataTable);

            if (dataTable.Rows.Count == 0)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                Category category = new Category();
                category.CategoryId = Convert.ToInt32(dataTable.Rows[0]["CategoryId"]);
                category.CategoryName = dataTable.Rows[0]["CategoryName"].ToString();
                category.ImageUrl = dataTable.Rows[0]["ImageUrl"].ToString();

                return View(category);
            }

        }


        [HttpPost]
        public IActionResult Delete(Category model)
        {
            SqlDataAdapter da = new SqlDataAdapter("select * from dbo.Categories where CategoryId=@CategoryId", sqlConnection);
            da.SelectCommand.Parameters.AddWithValue("CategoryId", model.CategoryId);

            DataTable dt = new DataTable();
            da.Fill(dt);

            if (dt.Rows.Count == 0)
            {
                ModelState.AddModelError(string.Empty, model.CategoryId + "numaralı kayıt bulunamadı.");
                return View(model);
            }
            else
            {
                SqlCommand cmd = new SqlCommand("delete from dbo.Categories where CategoryId=@CategoryId", sqlConnection);
                cmd.Parameters.AddWithValue("CategoryId", model.CategoryId);

                sqlConnection.Open();
                cmd.ExecuteNonQuery();
                sqlConnection.Close();

                return RedirectToAction(nameof(Index));
            }
        }


        public IActionResult GetCategories(int id)
        {
            List<Advertisement> list = new List<Advertisement>();

            SqlDataAdapter da = new SqlDataAdapter("select * from dbo.Advertisements where CategoryId=@CategoryId", sqlConnection);
            da.SelectCommand.Parameters.AddWithValue("CategoryId", id);
            DataTable dt = new DataTable();
            da.Fill(dt);


            foreach (DataRow data in dt.Rows)
            {
                Advertisement advertisement = new Advertisement
                {
                    TitleId = Convert.ToInt32(data["TitleId"]),
                    TitleName = (data["TitleName"]).ToString(),
                    CategoryId = Convert.ToInt32(data["CategoryId"]),
                    Description = (data["Description"]).ToString(),
                    ListelemeUrl = (data["ListelemeUrl"]).ToString(),
                    DetayUrl = (data["DetayUrl"]).ToString(),
                    Price = Convert.ToDecimal(data["Price"]),
                    PublicationDate = Convert.ToDateTime(data["PublicationDate"]),
                };
                list.Add(advertisement);
            }

            return View(list);
        }
    }
}

IlanSistemi/Views/Categories/Create.cshtml
@model IlanSistemi.Models.Entitites.Category

@{
    ViewData["Title"] = "Kategori Ekle";
}

<h4>Kategori Ekle</h4>
<hr />
<form asp-action="Create">
    <div class="row">
        @* border ekle classa  *@
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group mt-3 ">
                <input type="submit" value="Ekle" class="btn btn-light" />
            </div>
        </div>
    </div>
</form>

IlanSistemi/Views/Categories/Delete.cshtml
@model IlanSistemi.Models.Entitites.Category

@{
    ViewData["Title"] = "Kategori Sil";
}

<hr />
<dl class="row">
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.CategoryName)
    </dt>
    <dd class="col-sm-7">
        @Html.DisplayFor(model => model.CategoryName)
    </dd>
    <dt class="col-sm-3">
        @Html.DisplayNameFor(model => model.ImageUrl)
    </dt>
    <dd class="col-sm-7">
        @Html.DisplayFor(model => model.ImageUrl)
    </dd>
</dl>

<form asp-action="Delete">
    <input type="hidden" asp-for="CategoryId" />
    <input type="submit" value="sil" class="btn btn-danger" />
</form>
</div>

IlanSistemi/Views/Categories/Edit.cshtml
@model IlanSistemi.Models.Entitites.Category
@{
    ViewData["Title"] = "Kategori Düzenle";
}


<h4>Kategoriler</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="CategoryId" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="güncelle" class="btn btn-light" />
            </div>
        </form>
    </div>
</div>

IlanSistemi/Views/Categories/GetCategories.cshtml
@model  IEnumerable<IlanSistemi.Models.Entitites.Advertisement> 

@{
    ViewData["Title"] = "İlanlar";
}

<h1> </h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TitleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublicationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ListelemeUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DetayUrl)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TitleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublicationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ListelemeUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DetayUrl)
            </td>
            <td>
                    <a class="text-primary" asp-controller="Advertisements" asp-action="Edit" asp-route-id="@item.TitleId">güncelle</a> /
                    <a class="text-primary" asp-controller="Advertisements" asp-action="Delete" asp-route-id="@item.TitleId">sil</a>
            </td>
        </tr>
}
    </tbody>
</table>

IlanSistemi/Views/Categories/Index.cshtml
@model List<Category>

@{
    ViewData["Title"] = "Kategoriler";
}


<table class="table table-striped table-bordered">
    <thead>
        <tr style="background-color:darkgray">
            <th >
                @Html.DisplayNameFor(model => model.FirstOrDefault().CategoryName)
            </th>
            <th>
               Küçük Resim
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr><td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td>
                    <img src="#" class="img-thumbnail"/>
                    @Html.DisplayFor(modelItem => item.ImageUrl)
                </td>
                <td>
                    <a class="text-primary " asp-action="Edit" asp-route-categoryid="@item.CategoryId">güncelle</a> /
                    <a class="text-primary" asp-action="Delete" asp-route-categoryid="@item.CategoryId">sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<p>
    <a asp-action="Create">Kategori Ekle</a>
</p>